import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import ProviderApp from "@/components/ProviderApp";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { getServerSession } from "next-auth";
import SessionProvider from "@/utils/SessionProvider";
const inter = Cairo({ subsets: ["arabic"] });

export const metadata: Metadata = {
  title: "The Crew || Home",
  description: "Generated by create next app",
  icons: {
    icon: "/1.jpg", // /public path
  },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang="ar" dir="rtl">
      <head>
        <link rel="icon" href="/logo.png" sizes="any" />
      </head>
      <ProviderApp>
        <SessionProvider session={session}>
          <body className={inter.className + "overflow-hidden"}>
            <ToastContainer
              position="top-right"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="colored"
            />{" "}
            <ThemeProvider
              attribute="class"
              defaultTheme="light"
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
          </body>
        </SessionProvider>
      </ProviderApp>
    </html>
  );
}
