import NavBottom from "@/components/Client/NavBottom";
import NavClient from "@/components/Client/NavClient";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "The Crew || Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <NavClient />
      {children}
      <NavBottom />
    </>
  );
}
